"""Generate MkDocs API reference pages from the Python package tree."""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

import mkdocs_gen_files

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_ROOTS = [
    REPO_ROOT / "src",
    REPO_ROOT / "data",
]


def iter_python_modules() -> list[tuple[str, Path, Path, bool]]:
    """Return module metadata for docs generation.

    Each tuple contains:
    - dotted module path
    - repository-relative source path
    - docs output path under ``reference/``
    - whether the module is a package ``__init__``
    """
    modules: list[tuple[str, Path, Path, bool]] = []

    for root in SOURCE_ROOTS:
        if not root.exists():
            continue

        for source_path in sorted(root.rglob("*.py")):
            if "__pycache__" in source_path.parts:
                continue

            repo_relative = source_path.relative_to(REPO_ROOT)
            module_parts = list(repo_relative.with_suffix("").parts)
            is_package = module_parts[-1] == "__init__"

            if is_package:
                module_parts = module_parts[:-1]
                docs_path = Path("reference", *module_parts, "index.md")
            else:
                docs_path = Path("reference", *module_parts).with_suffix(".md")

            module_name = ".".join(module_parts)
            if not module_name:
                continue

            modules.append((module_name, repo_relative, docs_path, is_package))

    return modules
modules = iter_python_modules()
package_children: dict[str, list[tuple[str, Path]]] = defaultdict(list)
top_level_modules: dict[str, list[tuple[str, Path]]] = defaultdict(list)
package_pages: dict[str, Path] = {}

for module_name, source_path, docs_path, is_package in modules:
    parts = module_name.split(".")

    if is_package:
        package_pages[module_name] = docs_path
    if len(parts) > 1:
        package_children[".".join(parts[:-1])].append((module_name, docs_path))
    top_level_modules[parts[0]].append((module_name, docs_path))

for module_name, source_path, docs_path, is_package in modules:
    title = f"`{module_name}`"
    lines = [
        f"# {title}",
        "",
        "<!-- Auto-generated by docs/gen_ref_pages.py. -->",
        "",
        f"::: {module_name}",
        "",
    ]

    children = sorted(package_children.get(module_name, []))
    if children and is_package:
        lines.extend(
            [
                "## Submodules",
                "",
            ]
        )
        for child_name, child_path in children:
            if child_name == module_name:
                continue
            link_target = child_path.name if child_path.parent == docs_path.parent else str(
                child_path.relative_to(docs_path.parent)
            )
            lines.append(f"- [{child_name}]({link_target})")
        lines.append("")

    with mkdocs_gen_files.open(docs_path, "w") as fd:
        fd.write("\n".join(lines))

    mkdocs_gen_files.set_edit_path(docs_path, source_path)

index_lines = [
    "# API Reference",
    "",
    "These pages are generated from the Python package tree during the MkDocs build.",
    "",
    "Narrative operator guidance belongs in the manual docs pages; code-level details belong here.",
    "",
]

for package_name in sorted(top_level_modules):
    index_lines.append(f"## `{package_name}`")
    index_lines.append("")

    entries = sorted(top_level_modules[package_name])
    package_index = package_pages.get(package_name)
    if package_index is not None:
        index_lines.append(
            f"- [{package_name}]({package_index.relative_to('reference')})"
        )

    for module_name, docs_path in entries:
        if module_name == package_name:
            continue
        index_lines.append(
            f"- [{module_name}]({docs_path.relative_to('reference')})"
        )
    index_lines.append("")

with mkdocs_gen_files.open("reference/index.md", "w") as fd:
    fd.write("\n".join(index_lines))
