# MOFcat board configuration — instruments only.

instruments:
  uvvis:
      type: uvvis_ccs # USING MOCK UVVIS AS MOCK FILMETRICS
      offline: true
      vendor: thorlabs
      offset_x: 0.0
      offset_y: 0.0
      depth: 0.0
      safe_approach_height: 10.0
      measurement_height: 10.0
