# Sample board configuration for an EmStat potentiostat.

instruments:
  potentiostat:
    type: potentiostat
    vendor: emstat
    emstat_model: emstat4_lr
    emstat_data_directory: data/potentiostat
    offset_x: 0.0
    offset_y: 0.0
    depth: 0.0
    measurement_height: 3.0
